=== shihabuddin413/Onlinebookstore/data/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Root Element: catalog -->
  <xs:element name="catalog">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="book" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <!-- title element with sub-element publicationYear -->
              <xs:element name="title">
                <xs:complexType mixed="true">
                  <xs:sequence>
                    <xs:element name="publicationYear" type="xs:integer"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <!-- author element with sub-elements firstName and lastName -->
              <xs:element name="author">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="firstName" type="xs:string"/>
                    <xs:element name="lastName" type="xs:string"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <!-- Attributes for the book element -->
            <xs:attribute name="id" type="xs:string" use="required"/>
            <xs:attribute name="available" type="xs:boolean" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== shihabuddin413/Onlinebookstore/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="bookstore.xsd">
  
  <book id="B001" available="true">
    <title>The Great Gatsby
      <publicationYear>1925</publicationYear>
    </title>
    <author>
      <firstName>F. Scott</firstName>
      <lastName>Fitzgerald</lastName>
    </author>
  </book>

  <book id="B002" available="true">
    <title>To Kill a Mockingbird
      <publicationYear>1960</publicationYear>
    </title>
    <author>
      <firstName>Harper</firstName>
      <lastName>Lee</lastName>
    </author>
  </book>

  <book id="B003" available="false">
    <title>1984
      <publicationYear>1949</publicationYear>
    </title>
    <author>
      <firstName>George</firstName>
      <lastName>Orwell</lastName>
    </author>
  </book>

</catalog>
